//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 03:20:03 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://serjer.com/iban", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.serjer.iban;
